'use client';

import { useRef, useState } from 'react';

type Result = { food_name: string; calories: number; protein: number; carbs: number; fat: number };
export default function ScanPage() {
  const [image, setImage] = useState<string | null>(null); const [result, setResult] = useState<Result | null>(null); const [mealType, setMealType] = useState('lunch'); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(''); const [cameraOn, setCameraOn] = useState(false); const videoRef = useRef<HTMLVideoElement>(null); const streamRef = useRef<MediaStream | null>(null);
  async function startCamera() { try { streamRef.current = await navigator.mediaDevices.getUserMedia({ video: { facingMode: 'environment' }, audio: false }); if (videoRef.current) { videoRef.current.srcObject = streamRef.current; setCameraOn(true); } } catch { setMessage('Camera permission denied. Please allow camera access or choose a photo.'); } }
  function stopCamera() { streamRef.current?.getTracks().forEach(track=>track.stop()); streamRef.current = null; setCameraOn(false); }
  async function analyze(source: string) { setImage(source); setLoading(true); setMessage(''); setResult(null); const controller = new AbortController(); const timeout = window.setTimeout(() => controller.abort(), 30000); try { const response = await fetch('/api/analyze', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ imageBase64: source }), signal: controller.signal }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Analysis failed'); setResult(data); } catch (error) { setMessage(error instanceof DOMException && error.name === 'AbortError' ? 'Analysis took too long. Try a smaller or clearer image.' : error instanceof Error ? error.message : 'Analysis failed'); } finally { window.clearTimeout(timeout); setLoading(false); } }
  function capture() { const video = videoRef.current; if (!video) return; const canvas = document.createElement('canvas'); canvas.width = video.videoWidth; canvas.height = video.videoHeight; canvas.getContext('2d')?.drawImage(video, 0, 0); stopCamera(); analyze(canvas.toDataURL('image/jpeg', 0.85)); }
  function upload(file: File) { const reader = new FileReader(); reader.onload = () => { const source = String(reader.result); const img = new Image(); img.onload = () => { const max = 1280; const scale = Math.min(1, max / Math.max(img.width, img.height)); const canvas = document.createElement('canvas'); canvas.width = Math.round(img.width * scale); canvas.height = Math.round(img.height * scale); canvas.getContext('2d')?.drawImage(img, 0, 0, canvas.width, canvas.height); analyze(canvas.toDataURL('image/jpeg', 0.72)); }; img.src = source; }; reader.readAsDataURL(file); }
  async function save() { if (!result) return; const response = await fetch('/api/meals', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...result, meal_type: mealType, source: 'ai_scan' }) }); setMessage(response.ok ? 'Meal saved to today\'s diary.' : (await response.json()).error); }
  return <main className="min-h-screen bg-slate-50 p-6"><div className="mx-auto max-w-xl space-y-5"><a href="/dashboard" className="text-sm text-blue-600">← Back to dashboard</a><h1 className="text-3xl font-bold">Scan a meal</h1><div className="rounded-2xl border bg-white p-6 text-center">{cameraOn ? <video ref={videoRef} autoPlay playsInline className="mx-auto mb-4 max-h-72 w-full rounded-xl object-cover" /> : image ? <img src={image} alt="Selected meal" className="mx-auto mb-4 max-h-72 rounded-xl object-cover" /> : <div className="mb-4 flex h-64 items-center justify-center rounded-xl border-2 border-dashed text-slate-400">Take a photo or upload a meal</div>}<div className="flex flex-wrap justify-center gap-2">{cameraOn ? <button onClick={capture} className="rounded-lg bg-green-600 px-5 py-3 font-semibold text-white">Capture & analyze</button> : <button onClick={startCamera} className="rounded-lg bg-slate-900 px-5 py-3 font-semibold text-white">Open camera</button>}<label className="cursor-pointer rounded-lg bg-blue-600 px-5 py-3 font-semibold text-white">Choose photo<input type="file" accept="image/*" className="hidden" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])} /></label></div></div>{loading && <p className="text-center text-blue-600">AI analysis in progress...</p>}{result && <div className="rounded-2xl border border-green-200 bg-green-50 p-5"><h2 className="text-xl font-bold">{result.food_name}</h2><p className="mt-2">{result.calories} kcal · Protein {result.protein}g · Carbs {result.carbs}g · Fat {result.fat}g</p><div className="mt-4 flex gap-2"><select value={mealType} onChange={e=>setMealType(e.target.value)} className="rounded-lg border p-2"><option value="breakfast">Breakfast</option><option value="lunch">Lunch</option><option value="dinner">Dinner</option><option value="snack">Snack</option></select><button onClick={save} className="rounded-lg bg-green-600 px-4 py-2 font-semibold text-white">Save to diary</button></div></div>}{message && <p className="rounded-lg bg-white p-3 text-sm">{message}</p>}</div></main>;
}
